#!/bin/sh

# Abort if any command returns an error value
set -e

USER=grafsy
CONF=/etc/grafsy/grafsy.toml

# Following user part should be tested on both RPM and DEB systems
if ! getent group "${USER}" > /dev/null 2>&1 ; then
  groupadd --system "${USER}"
fi
GID=$(getent group "${USER}" | cut -d: -f 3)
if ! id "${USER}" > /dev/null 2>&1 ; then
  if ! adduser --system --home /dev/null --no-create-home \
    --gid "${GID}" --shell /bin/false \
    "${USER}"; then
      echo "The adduser command not found. Fallback to the useradd for compatibility"
      useradd --system --home /dev/null --no-create-home \
        --gid "${GID}" --shell /bin/false \
        "${USER}"
  fi
fi

if [ ! -e "${CONF}" ]; then
  echo "For use this software you have to create ${CONF} file. You could use /etc/grafsy/example/grafsy.toml as default"
else
  deb-systemd-invoke daemon-reload
  deb-systemd-helper enable grafsy.service
  deb-systemd-invoke restart grafsy.service
fi
